### ISSUE TITLE
BM3D outputs Full Range clip

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-denoise#112] opened 2024-03-07 17:40 UTC
On git latest, BM3D appears to output a full range clip. This happens with BM3DCPU, BM3DCuda, and BM3DCudaRTC, and at any input bitdepth.

```py
src = source("BDMV/FATE ZERO/AOA_FATEZERO_BOXSET_1/AOA_FATEZERO_BOXSET_1_D2/BDMV/STREAM/00003.m2ts", 16)[24:-24]
den = BM3DCudaRTC.denoise(src)
```

src

![image](https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise/assets/42927908/78603c60-acb9-4e5c-bc55-5f3ee8fe8854)

bm3d

![image](https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise/assets/42927908/5f5b9526-b19a-463d-bbe3-5d594a213198)

**Comment by Setsugennoao** [comment] 2024-03-07 20:39
Duplicate of #102

**Closed by Setsugennoao** 2024-03-07 20:39 UTC

**Comment by Vodes** [comment] 2024-03-07 21:04
Then fix it :)
